// <auto-generated />
using System;
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921040106_AddOrganizacionActividadEconomica")]
    partial class AddOrganizacionActividadEconomica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "IsAccepted");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("BackendAPI.Models.DashboardCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TabKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DashboardCards");
                });

            modelBuilder.Entity("BackendAPI.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExpirationDate");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BackendAPI.Models.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DocumentTemplates");
                });

            modelBuilder.Entity("BackendAPI.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BackendAPI.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackendAPI.Models.SassService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SassServices");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstDesignationFunction", b =>
                {
                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uuid");

                    b.Property<int>("FunctionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.HasKey("DesignationId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("SgSstDesignationFunctions");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstFunctionCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SgSstFunctionCatalogs");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstResponsibleDesignation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoberturaCentroTrabajo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoberturaDetalle")
                        .HasColumnType("text");

                    b.Property<string>("ComplianceNota")
                        .HasColumnType("text");

                    b.Property<int>("ComplianceStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Curso50HorasAprobado")
                        .HasColumnType("boolean");

                    b.Property<string>("EmpleadorAceptaCargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpleadorAceptaDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmpleadorAceptaFechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmpleadorAceptaNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpleadorFirmaImagen")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion20Horas")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenciaSstExpedidaPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenciaSstNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NivelCompetencia")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizacionActividadEconomica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizacionDepartamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizacionMunicipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizacionNivelRiesgoArl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsableAceptaDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResponsableAceptaFechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponsableAceptaLicencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsableAceptaNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsableCargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsableFirmaImagen")
                        .HasColumnType("text");

                    b.Property<string>("ResponsableNombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsableNumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsableTipoDocumento")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuscripcionCiudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SuscripcionFecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "Version")
                        .IsUnique();

                    b.ToTable("SgSstResponsibleDesignations");
                });

            modelBuilder.Entity("BackendAPI.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CentrosTrabajo")
                        .HasColumnType("integer");

                    b.Property<string>("Ciiu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaseRiesgo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DigitoVerificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NitRuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroTrabajadores")
                        .HasColumnType("integer");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsableSst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TieneBrigada")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneComiteConvivencia")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneContratistas")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneCopasst")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemporaryPassword")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupabaseAuthId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SupabaseAuthId")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsDisabled");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DashboardCardTenant", b =>
                {
                    b.Property<int>("EnabledDashboardCardsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantsId")
                        .HasColumnType("uuid");

                    b.HasKey("EnabledDashboardCardsId", "TenantsId");

                    b.HasIndex("TenantsId");

                    b.ToTable("TenantDashboardCards", (string)null);
                });

            modelBuilder.Entity("DashboardCardUser", b =>
                {
                    b.Property<int>("EnabledDashboardCardsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("EnabledDashboardCardsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserDashboardCards", (string)null);
                });

            modelBuilder.Entity("SassServiceTenant", b =>
                {
                    b.Property<int>("EnabledServicesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantsId")
                        .HasColumnType("uuid");

                    b.HasKey("EnabledServicesId", "TenantsId");

                    b.HasIndex("TenantsId");

                    b.ToTable("TenantServices", (string)null);
                });

            modelBuilder.Entity("SassServiceUser", b =>
                {
                    b.Property<int>("EnabledServicesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("EnabledServicesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserServices", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.Alert", b =>
                {
                    b.HasOne("BackendAPI.Models.User", "Recipient")
                        .WithMany("Alerts")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("BackendAPI.Models.Document", b =>
                {
                    b.HasOne("BackendAPI.Models.Tenant", "Tenant")
                        .WithMany("Documents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BackendAPI.Models.Employee", b =>
                {
                    b.HasOne("BackendAPI.Models.Tenant", "Tenant")
                        .WithMany("Employees")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstDesignationFunction", b =>
                {
                    b.HasOne("BackendAPI.Models.SgSstResponsibleDesignation", "Designation")
                        .WithMany("DesignationFunctions")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.SgSstFunctionCatalog", "Function")
                        .WithMany("DesignationFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Designation");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstResponsibleDesignation", b =>
                {
                    b.HasOne("BackendAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.HasOne("BackendAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DashboardCardTenant", b =>
                {
                    b.HasOne("BackendAPI.Models.DashboardCard", null)
                        .WithMany()
                        .HasForeignKey("EnabledDashboardCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DashboardCardUser", b =>
                {
                    b.HasOne("BackendAPI.Models.DashboardCard", null)
                        .WithMany()
                        .HasForeignKey("EnabledDashboardCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SassServiceTenant", b =>
                {
                    b.HasOne("BackendAPI.Models.SassService", null)
                        .WithMany()
                        .HasForeignKey("EnabledServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SassServiceUser", b =>
                {
                    b.HasOne("BackendAPI.Models.SassService", null)
                        .WithMany()
                        .HasForeignKey("EnabledServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstFunctionCatalog", b =>
                {
                    b.Navigation("DesignationFunctions");
                });

            modelBuilder.Entity("BackendAPI.Models.SgSstResponsibleDesignation", b =>
                {
                    b.Navigation("DesignationFunctions");
                });

            modelBuilder.Entity("BackendAPI.Models.Tenant", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Employees");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
